import { ConflictException, Injectable } from "@nestjs/common";
import { type CreateUserInput } from "@zapp/entities";
import {
	ColumnType,
	Generated,
	Kysely,
	type SelectQueryBuilder,
	SqliteDialect,
} from "kysely";
import { isSqliteUniqueConstraintError } from "../common/sqlite-error.util";
import { DatabaseService } from "../database/database.service";

type AutoGenerated<T> = ColumnType<T, T | undefined, T>;
type SelectableRow<T> = {
	[K in keyof T]: T[K] extends ColumnType<infer S, unknown, unknown> ? S : T[K];
};

type UserTable = {
	id: Generated<number>;
	name: string;
	email: string;
	phone: AutoGenerated<string | null>;
	avatar_url: AutoGenerated<string | null>;
	role: AutoGenerated<string>;
	is_active: AutoGenerated<number>;
	created_at: AutoGenerated<string>;
	updated_at: AutoGenerated<string>;
};

type DatabaseSchema = {
	users: UserTable;
};

export type UserSortBy =
	| "id"
	| "name"
	| "email"
	| "role"
	| "created_at"
	| "updated_at";

export type UserFilters = {
	roles?: string[];
	isActive?: boolean;
	search?: string;
	createdAfter?: string;
	createdBefore?: string;
	sortBy?: UserSortBy;
	sortDir?: "asc" | "desc";
	pagination?: "page" | "cursor";
	page?: number;
	pageSize?: number;
	cursor?: number;
	limit?: number;
};

type UserRow = SelectableRow<UserTable>;

type PagePaginationResult = {
	mode: "page";
	page: number;
	pageSize: number;
	total: number;
	totalPages: number;
};

type CursorPaginationResult = {
	mode: "cursor";
	limit: number;
	nextCursor: number | null;
	hasMore: boolean;
};

type PageUsersResult = {
	items: UserRow[];
	pagination: PagePaginationResult;
};

type CursorUsersResult = {
	items: UserRow[];
	pagination: CursorPaginationResult;
};

type FindAllResult = UserRow[] | PageUsersResult | CursorUsersResult;

@Injectable()
export class UsersService {
	private kyselyDb?: Kysely<DatabaseSchema>;

	constructor(private readonly db: DatabaseService) {}

	private getKyselyDb() {
		if (!this.kyselyDb) {
			this.kyselyDb = new Kysely<DatabaseSchema>({
				dialect: new SqliteDialect({
					database: this.db.getConnection(),
				}),
			});
		}

		return this.kyselyDb;
	}

	private applyUserFilters<
		// biome-ignore lint/complexity/noBannedTypes: Kysely's SelectQueryBuilder requires {} as the initial selection type
		T extends SelectQueryBuilder<DatabaseSchema, "users", {}>,
	>(query: T, filters: UserFilters): T {
		let filteredQuery = query;

		if (filters.roles?.length) {
			filteredQuery = filteredQuery.where("role", "in", filters.roles) as T;
		}

		if (filters.isActive !== undefined) {
			filteredQuery = filteredQuery.where(
				"is_active",
				"=",
				filters.isActive ? 1 : 0,
			) as T;
		}

		const searchTerm = filters.search?.trim();
		if (searchTerm) {
			const searchPattern = `%${searchTerm}%`;
			filteredQuery = filteredQuery.where((eb) =>
				eb.or([
					eb("name", "like", searchPattern),
					eb("email", "like", searchPattern),
					eb("phone", "like", searchPattern),
				]),
			) as T;
		}

		if (filters.createdAfter) {
			filteredQuery = filteredQuery.where(
				"created_at",
				">=",
				filters.createdAfter,
			) as T;
		}

		if (filters.createdBefore) {
			filteredQuery = filteredQuery.where(
				"created_at",
				"<=",
				filters.createdBefore,
			) as T;
		}

		return filteredQuery;
	}

	private applySort<
		// biome-ignore lint/complexity/noBannedTypes: Kysely's SelectQueryBuilder requires {} as the initial selection type
		T extends SelectQueryBuilder<DatabaseSchema, "users", {}>,
	>(query: T, filters: UserFilters, forceIdSort = false): T {
		const sortDirection = filters.sortDir === "desc" ? "desc" : "asc";
		const sortBy = forceIdSort ? "id" : (filters.sortBy ?? "id");
		let sortedQuery = query;

		switch (sortBy) {
			case "name":
				sortedQuery = sortedQuery.orderBy("name", sortDirection) as T;
				break;
			case "email":
				sortedQuery = sortedQuery.orderBy("email", sortDirection) as T;
				break;
			case "role":
				sortedQuery = sortedQuery.orderBy("role", sortDirection) as T;
				break;
			case "created_at":
				sortedQuery = sortedQuery.orderBy("created_at", sortDirection) as T;
				break;
			case "updated_at":
				sortedQuery = sortedQuery.orderBy("updated_at", sortDirection) as T;
				break;
			default:
				sortedQuery = sortedQuery.orderBy("id", sortDirection) as T;
				break;
		}

		if (sortBy !== "id") {
			sortedQuery = sortedQuery.orderBy("id", sortDirection) as T;
		}

		return sortedQuery;
	}

	private buildUsersQuery(filters: UserFilters = {}) {
		return this.applyUserFilters(
			this.getKyselyDb().selectFrom("users"),
			filters,
		).selectAll("users");
	}

	private buildCountQuery(filters: UserFilters = {}) {
		return this.applyUserFilters(
			this.getKyselyDb().selectFrom("users"),
			filters,
		).select(({ fn }) => fn.count<number>("id").as("total"));
	}

	async findAll(filters: UserFilters = {}): Promise<FindAllResult> {
		const query = this.buildUsersQuery(filters);
		const paginationMode =
			filters.pagination ??
			(filters.cursor !== undefined
				? "cursor"
				: filters.page
					? "page"
					: undefined);

		if (paginationMode === "page") {
			const page = Math.max(1, filters.page ?? 1);
			const pageSize = Math.min(100, Math.max(1, filters.pageSize ?? 20));
			const offset = (page - 1) * pageSize;
			const [items, countResult] = await Promise.all([
				this.applySort(query, filters).limit(pageSize).offset(offset).execute(),
				this.buildCountQuery(filters).executeTakeFirst(),
			]);

			const total = Number(countResult?.total ?? 0);
			const totalPages = Math.max(1, Math.ceil(total / pageSize));
			return {
				items,
				pagination: {
					mode: "page",
					page,
					pageSize,
					total,
					totalPages,
				},
			};
		}

		if (paginationMode === "cursor") {
			const limit = Math.min(
				100,
				Math.max(1, filters.limit ?? filters.pageSize ?? 20),
			);
			const sortDirection = filters.sortDir === "desc" ? "desc" : "asc";
			let cursorQuery = this.applySort(query, filters, true);

			if (filters.cursor !== undefined) {
				cursorQuery =
					sortDirection === "desc"
						? cursorQuery.where("id", "<", filters.cursor)
						: cursorQuery.where("id", ">", filters.cursor);
			}

			const rows = await cursorQuery.limit(limit + 1).execute();
			const hasMore = rows.length > limit;
			const items = hasMore ? rows.slice(0, limit) : rows;
			const nextCursor = hasMore ? (items.at(-1)?.id ?? null) : null;

			return {
				items,
				pagination: {
					mode: "cursor",
					limit,
					nextCursor,
					hasMore,
				},
			};
		}

		return this.applySort(query, filters).execute();
	}

	findById(id: number) {
		return this.getKyselyDb()
			.selectFrom("users")
			.selectAll()
			.where("id", "=", id)
			.executeTakeFirst();
	}

	async create(data: CreateUserInput) {
		try {
			const result = await this.getKyselyDb()
				.insertInto("users")
				.values({
					name: data.name,
					email: data.email,
					phone: data.phone ?? null,
				})
				.executeTakeFirst();

			const insertedId = Number(result.insertId);
			return this.findById(insertedId);
		} catch (error) {
			if (isSqliteUniqueConstraintError(error, "users.email")) {
				throw new ConflictException("A user with this email already exists.");
			}

			throw error;
		}
	}
}
