import { ConflictException, Inject, Injectable } from "@nestjs/common";
import { type CreateProductInput } from "@zapp/entities";
import {
	ColumnType,
	Generated,
	Kysely,
	type SelectQueryBuilder,
	SqliteDialect,
	sql,
} from "kysely";
import { isSqliteUniqueConstraintError } from "../common/sqlite-error.util";
import { DatabaseService } from "../database/database.service";

type AutoGenerated<T> = ColumnType<T, T | undefined, T>;
type SelectableRow<T> = {
	[K in keyof T]: T[K] extends ColumnType<infer S, unknown, unknown> ? S : T[K];
};

type ProductTable = {
	id: Generated<number>;
	name: string;
	description: string | null;
	price: number;
	sku: string;
	category: string;
	brand: string | null;
	image_url: AutoGenerated<string | null>;
	thumbnail_url: AutoGenerated<string | null>;
	weight: AutoGenerated<number | null>;
	rating: AutoGenerated<number>;
	review_count: AutoGenerated<number>;
	in_stock: AutoGenerated<number>;
	stock_quantity: AutoGenerated<number>;
	discount_percent: AutoGenerated<number>;
	tags: AutoGenerated<string | null>;
	created_at: AutoGenerated<string>;
	updated_at: AutoGenerated<string>;
};

type DatabaseSchema = {
	products: ProductTable;
};

export type ProductFilters = {
	categories?: string[];
	brands?: string[];
	minPrice?: number;
	maxPrice?: number;
	inStock?: boolean;
	search?: string;
	sortBy?: ProductSortBy;
	sortDir?: "asc" | "desc";
	pagination?: "page" | "cursor";
	page?: number;
	pageSize?: number;
	cursor?: number;
	limit?: number;
};

export type ProductSortBy =
	| "id"
	| "name"
	| "price"
	| "created_at"
	| "updated_at";

type ProductRow = SelectableRow<ProductTable> & {
	in_stock: number;
};

type PagePaginationResult = {
	mode: "page";
	page: number;
	pageSize: number;
	total: number;
	totalPages: number;
};

type CursorPaginationResult = {
	mode: "cursor";
	limit: number;
	nextCursor: number | null;
	hasMore: boolean;
};

type PageProductsResult = {
	items: ProductRow[];
	pagination: PagePaginationResult;
};

type CursorProductsResult = {
	items: ProductRow[];
	pagination: CursorPaginationResult;
};

type FindAllResult = ProductRow[] | PageProductsResult | CursorProductsResult;

@Injectable()
export class ProductsService {
	private kyselyDb?: Kysely<DatabaseSchema>;

	constructor(
		@Inject(DatabaseService)
		private readonly db: DatabaseService,
	) {}

	private getKyselyDb() {
		if (!this.kyselyDb) {
			this.kyselyDb = new Kysely<DatabaseSchema>({
				dialect: new SqliteDialect({
					database: this.db.getConnection(),
				}),
			});
		}

		return this.kyselyDb;
	}

	private applyProductFilters<
		// biome-ignore lint/complexity/noBannedTypes: Kysely's SelectQueryBuilder requires {} as the initial selection type
		T extends SelectQueryBuilder<DatabaseSchema, "products", {}>,
	>(query: T, filters: ProductFilters): T {
		let filteredQuery = query;

		if (filters.categories?.length) {
			filteredQuery = filteredQuery.where(
				"category",
				"in",
				filters.categories,
			) as T;
		}

		if (filters.brands?.length) {
			filteredQuery = filteredQuery.where("brand", "in", filters.brands) as T;
		}

		if (filters.minPrice !== undefined) {
			filteredQuery = filteredQuery.where("price", ">=", filters.minPrice) as T;
		}

		if (filters.maxPrice !== undefined) {
			filteredQuery = filteredQuery.where("price", "<=", filters.maxPrice) as T;
		}

		if (filters.inStock !== undefined) {
			filteredQuery = (
				filters.inStock
					? filteredQuery.where("stock_quantity", ">", 0)
					: filteredQuery.where("stock_quantity", "<=", 0)
			) as T;
		}

		const searchTerm = filters.search?.trim();
		if (searchTerm) {
			const searchPattern = `%${searchTerm}%`;
			filteredQuery = filteredQuery.where((eb) =>
				eb.or([
					eb("name", "like", searchPattern),
					eb("description", "like", searchPattern),
					eb("sku", "like", searchPattern),
					eb("category", "like", searchPattern),
					eb("brand", "like", searchPattern),
					eb("tags", "like", searchPattern),
				]),
			) as T;
		}

		return filteredQuery;
	}

	private buildProductsQuery(filters: ProductFilters = {}) {
		return this.applyProductFilters(
			this.getKyselyDb().selectFrom("products"),
			filters,
		)
			.selectAll("products")
			.select((eb) =>
				sql<number>`CASE WHEN ${eb.ref("stock_quantity")} > 0 THEN 1 ELSE 0 END`.as(
					"in_stock",
				),
			);
	}

	private buildCountQuery(filters: ProductFilters = {}) {
		return this.applyProductFilters(
			this.getKyselyDb().selectFrom("products"),
			filters,
		).select(({ fn }) => fn.count<number>("id").as("total"));
	}

	private applySort<
		// biome-ignore lint/complexity/noBannedTypes: Kysely's SelectQueryBuilder requires {} as the initial selection type
		T extends SelectQueryBuilder<DatabaseSchema, "products", {}>,
	>(query: T, filters: ProductFilters, forceIdSort = false): T {
		const sortDirection = filters.sortDir === "desc" ? "desc" : "asc";
		const sortBy = forceIdSort ? "id" : (filters.sortBy ?? "id");
		let sortedQuery = query;

		switch (sortBy) {
			case "name":
				sortedQuery = sortedQuery.orderBy("name", sortDirection) as T;
				break;
			case "price":
				sortedQuery = sortedQuery.orderBy("price", sortDirection) as T;
				break;
			case "created_at":
				sortedQuery = sortedQuery.orderBy("created_at", sortDirection) as T;
				break;
			case "updated_at":
				sortedQuery = sortedQuery.orderBy("updated_at", sortDirection) as T;
				break;
			default:
				sortedQuery = sortedQuery.orderBy("id", sortDirection) as T;
				break;
		}

		if (sortBy !== "id") {
			sortedQuery = sortedQuery.orderBy("id", sortDirection) as T;
		}

		return sortedQuery;
	}

	async findAll(filters: ProductFilters = {}): Promise<FindAllResult> {
		const query = this.buildProductsQuery(filters);
		const paginationMode =
			filters.pagination ??
			(filters.cursor !== undefined
				? "cursor"
				: filters.page
					? "page"
					: undefined);

		if (paginationMode === "page") {
			const page = Math.max(1, filters.page ?? 1);
			const pageSize = Math.min(100, Math.max(1, filters.pageSize ?? 20));
			const offset = (page - 1) * pageSize;

			const [items, countResult] = await Promise.all([
				this.applySort(query, filters).limit(pageSize).offset(offset).execute(),
				this.buildCountQuery(filters).executeTakeFirst(),
			]);

			const total = Number(countResult?.total ?? 0);
			const totalPages = Math.max(1, Math.ceil(total / pageSize));

			return {
				items,
				pagination: {
					mode: "page",
					page,
					pageSize,
					total,
					totalPages,
				},
			};
		}

		if (paginationMode === "cursor") {
			const limit = Math.min(
				100,
				Math.max(1, filters.limit ?? filters.pageSize ?? 20),
			);
			const sortDirection = filters.sortDir === "desc" ? "desc" : "asc";
			let cursorQuery = this.applySort(query, filters, true);

			if (filters.cursor !== undefined) {
				cursorQuery =
					sortDirection === "desc"
						? cursorQuery.where("id", "<", filters.cursor)
						: cursorQuery.where("id", ">", filters.cursor);
			}

			const rows = await cursorQuery.limit(limit + 1).execute();
			const hasMore = rows.length > limit;
			const items = hasMore ? rows.slice(0, limit) : rows;
			const nextCursor = hasMore ? (items.at(-1)?.id ?? null) : null;

			return {
				items,
				pagination: {
					mode: "cursor",
					limit,
					nextCursor,
					hasMore,
				},
			};
		}

		return this.applySort(query, filters).execute();
	}

	async findBrands(): Promise<string[]> {
		const rows = await this.getKyselyDb()
			.selectFrom("products")
			.select("brand")
			.where("brand", "is not", null)
			.orderBy("brand", "asc")
			.execute();

		return Array.from(
			new Set(
				rows
					.map((row) => row.brand?.trim())
					.filter((brand): brand is string => Boolean(brand)),
			),
		).sort((leftBrand, rightBrand) => leftBrand.localeCompare(rightBrand));
	}

	findById(id: number) {
		return this.getKyselyDb()
			.selectFrom("products")
			.selectAll()
			.select((eb) =>
				sql<number>`CASE WHEN ${eb.ref("stock_quantity")} > 0 THEN 1 ELSE 0 END`.as(
					"in_stock",
				),
			)
			.where("id", "=", id)
			.executeTakeFirst();
	}

	async create(data: CreateProductInput) {
		try {
			const result = await this.getKyselyDb()
				.insertInto("products")
				.values({
					name: data.name,
					description: data.description ?? null,
					price: data.price,
					sku: data.sku,
					category: data.category,
					brand: data.brand ?? null,
				})
				.executeTakeFirst();

			const insertedId = Number(result.insertId);
			return this.findById(insertedId);
		} catch (error) {
			if (isSqliteUniqueConstraintError(error, "products.sku")) {
				throw new ConflictException("A product with this SKU already exists.");
			}

			throw error;
		}
	}
}
